# Generated by Django 3.0.3 on 2020-04-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uni_video_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
