# Generated by Django 3.0.3 on 2020-04-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20200404_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthread',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
