# Generated by Django 3.0.3 on 2020-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200404_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthread',
            name='num_comments',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
