# Generated by Django 3.0.3 on 2020-04-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20200404_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], default='All', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], default='All', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentreply',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='replied_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.Comment'),
        ),
    ]
