# Generated by Django 3.0.3 on 2020-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_youtubedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedata',
            name='tags',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
