# Generated by Django 3.0.3 on 2020-04-22 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0011_youtubedata_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedata',
            name='thumbnail_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], max_length=30),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], max_length=30),
        ),
        migrations.CreateModel(
            name='SearchFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(choices=[('Visual', 'Visual'), ('Verbal', 'Verbal'), ('Aural', 'Aural'), ('Kinesthetic', 'Kinesthetic'), ('Logical', 'Logical')], max_length=3000)),
                ('time_length', multiselectfield.db.fields.MultiSelectField(choices=[('short', 'Short (0 - 5 minutes)'), ('medium', 'Medium (5 - 15 minutes)'), ('semi-long', 'Semi-Long (15 - 25 minutes)'), ('long', 'Long (25+ minutes)')], max_length=27)),
                ('sort_by', models.CharField(choices=[('Time', 'Shortest Time'), ('Approval', 'Approval (Rating/Likes)'), ('Views', 'Most Views'), ('Comments', 'Most Comments')], max_length=3000)),
                ('sort_using', models.CharField(choices=[('Unitube', 'Unitube Data'), ('Youtube', 'Youtube Data')], max_length=3000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
