# Generated by Django 3.0.3 on 2020-04-24 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0014_auto_20200424_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='class_choice',
            field=models.CharField(choices=[('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], max_length=30),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='class_choice',
            field=models.CharField(choices=[('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='class_choice',
            field=models.CharField(choices=[('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], max_length=30),
        ),
        migrations.CreateModel(
            name='ClassFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', multiselectfield.db.fields.MultiSelectField(choices=[('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], default='', max_length=73)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
