# Generated by Django 3.0.3 on 2020-04-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20200424_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedata',
            name='time_length_str',
            field=models.TextField(default='00:00:00'),
        ),
    ]
