# Generated by Django 3.0.3 on 2020-04-25 07:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_auto_20200425_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfilters',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('All', 'All'), ('General', 'General'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340'), ('Cos424', 'Cos424')], default='General', max_length=84),
        ),
        migrations.AlterField(
            model_name='comment',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('General', 'General'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340'), ('Cos424', 'Cos424')], max_length=30),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('General', 'General'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340'), ('Cos424', 'Cos424')], max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('General', 'General'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340'), ('Cos424', 'Cos424')], max_length=30),
        ),
    ]
