# Generated by Django 3.0.3 on 2020-04-27 06:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_auto_20200425_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfilters',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('All', 'All'), ('General', 'General'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340'), ('Cos424', 'Cos424')], default='All', max_length=84),
        ),
        migrations.AlterField(
            model_name='searchfilters',
            name='learning_style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Visual', 'Visual'), ('Verbal', 'Verbal'), ('Aural', 'Aural'), ('Kinesthetic', 'Kinesthetic'), ('Logical', 'Logical')], default='', max_length=3000),
        ),
    ]
