# Generated by Django 3.0.3 on 2020-04-28 03:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20200427_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='negatives',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('-Visual', 'Poor or no visualizations'), ('-Depth', 'No in-depth explanation'), ('-Speak', 'Boring speaker, or hard to understand'), ('-Demo', 'No demo or walkthrough'), ('-voiceover', 'No voiceover')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='positives',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('+Visual', 'Great visualizations'), ('+Depth', 'In-depth Explanation'), ('+Speak', 'Engaging Speaker'), ('+Demo', 'Uses/walksthrough an example(s)')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='recommended_speed',
            field=models.CharField(choices=[('Normal', 'Normal'), ('0.25', '0.25x'), ('0.50', '0.50x'), ('0.75', '0.75x'), ('1.25', '1.25x'), ('1.50', '1.50x'), ('1.75', '1.75x'), ('2', '2x')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='class_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('All', 'All'), ('General', 'General'), ('Cos109', 'Cos109'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos306', 'Cos306'), ('Cos314', 'Cos314'), ('Cos315', 'Cos315'), ('Cos320', 'Cos320'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340'), ('Cos424', 'Cos424')], default='', max_length=200),
        ),
    ]
