# Generated by Django 3.0.3 on 2020-03-30 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(choices=[('Aural', 'Aural'), ('Verbal', 'Verbal'), ('Kinesthetic', 'Kinesthetic'), ('Visual', 'Visual'), ('Logical', 'Logical')], max_length=30)),
                ('year_in_school', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate Student'), ('Postdoc', 'Postdoc'), ('Not in School', 'Not in School')], default='Unknown', max_length=20)),
                ('major', models.CharField(default='Unknown', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
