# Generated by Django 3.0.3 on 2020-03-31 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learning_style',
            field=models.CharField(choices=[('', ''), ('Visual', 'Visual'), ('Verbal', 'Verbal'), ('Aural', 'Aural'), ('Kinesthetic', 'Kinesthetic'), ('Logical', 'Logical')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('', ''), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate Student'), ('Postdoc', 'Postdoc'), ('Not in School', 'Not in School')], default='Unknown', max_length=100),
        ),
    ]
