# Generated by Django 3.0.3 on 2020-04-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200331_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learning_style',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Verbal', 'Verbal'), ('Aural', 'Aural'), ('Kinesthetic', 'Kinesthetic'), ('Logical', 'Logical')], max_length=100),
        ),
    ]
