# Generated by Django 3.0.3 on 2020-03-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
