# Generated by Django 3.0.3 on 2020-03-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_video_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='class_choice',
            field=models.CharField(choices=[('All', 'All'), ('Cos126', 'Cos126'), ('Cos217', 'Cos217'), ('Cos226', 'Cos226'), ('Cos333', 'Cos333'), ('Cos340', 'Cos340')], max_length=30),
        ),
    ]
